### ISSUE TITLE
SSL labs check isnt working with check_mk 1.2.8

### ISSUE THREAD

**Issue by stemod** [lgbff/lgb_check_mk_plugins#9]
``` 
General error: Check parameter definition for ssllabs_grade has type Dictionary, but match_type first
```

**Comment by patatman** [comment]
This can be fixed by renaming a file, and editing /opt/omd/sites/sitename/local/share/check_mk/web/plugins/wato/ssllabs_check_pameters.py

Edit line 37:
from:
`"first",`
to:
`"dict",`

After this, the error will be gone, but the check won't work yet. You need to rename the file:
`/opt/omd/sites/sitename/local/share/check_mk/checks/ssllabs`
to:
`/opt/omd/sites/bosqom4/local/share/check_mk/checks/ssllabs_grade`
After this everything should work.
Tested on 2 different check_mk servers running 1.2.8p2

**Comment by lgbff** [comment]
Sorry, ich forgot this patch, the mkp file was correct.
98000e33

**Comment by stemod** [comment]
Could you create a new mkp?

**Comment by lgbff** [comment]
I has, but i don't upload to mk :-(
I ticket on mk is opened...
